language: node_js
node_js:
- '6'
- '8'
- '10'
cache:
  yarn: true
env:
  global:
    secure: MYvJT6EHiECzSeBtllYkPeehNsgCpLMApM0TVyAL9BxKvL01jKwoR/KQ48Y0gm8DVMa7PjGR9N6Iu57jPxHfVR+QGNoQkFNsXWMq/Cp6pEOIhCHHqB0us2emxcfWbrJvzQ6SFUtNoAQ2U3Rgcf8ZQZOcWuGQDmYop9+pnwiAJokjTZ5u4WixBMkGm6k+naJCxNYVkCpS73kbyjilK/CY5DgL19vsrWyAUsoUr3edr91VFV7Oh2UKhidKcsaoKko+NGFerQXVivoWiYrLaEDpt4eCd3hWIShizIWd6FEpAbhBpDAd70UR0i4OVzv6GYDW1eMC2B+JnbLEZvzCdu2C4zuwgBwS2897mPAh2nCfJt8HLyksRlq7x7p70HQdQjMce8nQeuMa81FLa+AXJZAQVJOtwVybdWgScsERPTqZEurgv3Cy88PTvKQ7Zgx+sbhVrUagpbyMvAcZ8VmqfL829GWWaBj6ih+ZNUGq5XCaBu8zrG8L9yicE8inEHgxhO09kbMKAa9qHFfRODy+qJkE70aDH2gqaclk0VVd7FqgaJsdYRVEzBUelErL8uCc4vMbgCwtdGA05ZptZ2useQHOq4s627qpNtTpGvkGUTpcZaYFPodNpFCtTQV0fvYAzZq0SnqqJasDzNehLwGMtI9rhzgsg12k85kW/klCtbFU4Us=
before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
script:
- yarn run test-ci
after_script: greenkeeper-lockfile-upload
deploy:
  provider: npm
  email: rplan-ci@actano.de
  api_key:
    secure: Aeyr+ng0L+szR0AnZEO+Q0LBlEA/iRiTRCOuO9++OWTxLSKsquSFqPveB3vf6gNtpPVpTUHg7xBwjaCyzKnWhcxntbCp9h4JILGfAzZv8SX2K0J9qg48W8PkmlO5sCuW8lGck26M78vGm8mQZoG6g+dVXfVpHAxvtuzDCOv4ro2i+tMSSI28HAHhp2QTDwdRn3RMTAxlAc85XXxgvFdc+t66lj+L9tI9G0xIfcZS8dl/EOFd1P3OP4KY4Ky91Rri88G0iIR03Ud+7J6f4WLSByxBYPQ8cjjpWInZvFcAu0ov6RXIopI3g1qkQs2exGOpFD70lAnodCg0SLjulAskX+cLp4ZA12mSX9z+jnZGDb74hsyAQmZr5VKBxSRsuL3XggM1k6TRrYqC51tASBlfTDQMhHHQh3ZopWzKr0sAMp1JL1mArLh/AW08yRPdNOWtloIGlwwFZCdKF4Yrhk2wO1uWu52Nb+u7CgpgTpBeEsIKkfUkkj/oyiUcNJOePEN3dtRopY/ZiTfJg9hgpSPDnLu/l2PTIDu+HeK/tDTOMh9esUgHKUZke5xdtFLmvomoNf7bT08JgVWf7f9MNQbW1fIRLYIlT0AenjV+OYgM7nIiRwX4OdznJjccP0SN9KQABOxliG5Ii2GDlrGqObka285S8oKpUIZA7cDl8Pvys0g=
  on:
    tags: true
    repo: actano/yourchoice
    node: '6'
