language: node_js
node_js:
- '6'
- '8'
- '10'
cache:
  yarn: true
env:
  global:
    secure: MYvJT6EHiECzSeBtllYkPeehNsgCpLMApM0TVyAL9BxKvL01jKwoR/KQ48Y0gm8DVMa7PjGR9N6Iu57jPxHfVR+QGNoQkFNsXWMq/Cp6pEOIhCHHqB0us2emxcfWbrJvzQ6SFUtNoAQ2U3Rgcf8ZQZOcWuGQDmYop9+pnwiAJokjTZ5u4WixBMkGm6k+naJCxNYVkCpS73kbyjilK/CY5DgL19vsrWyAUsoUr3edr91VFV7Oh2UKhidKcsaoKko+NGFerQXVivoWiYrLaEDpt4eCd3hWIShizIWd6FEpAbhBpDAd70UR0i4OVzv6GYDW1eMC2B+JnbLEZvzCdu2C4zuwgBwS2897mPAh2nCfJt8HLyksRlq7x7p70HQdQjMce8nQeuMa81FLa+AXJZAQVJOtwVybdWgScsERPTqZEurgv3Cy88PTvKQ7Zgx+sbhVrUagpbyMvAcZ8VmqfL829GWWaBj6ih+ZNUGq5XCaBu8zrG8L9yicE8inEHgxhO09kbMKAa9qHFfRODy+qJkE70aDH2gqaclk0VVd7FqgaJsdYRVEzBUelErL8uCc4vMbgCwtdGA05ZptZ2useQHOq4s627qpNtTpGvkGUTpcZaYFPodNpFCtTQV0fvYAzZq0SnqqJasDzNehLwGMtI9rhzgsg12k85kW/klCtbFU4Us=
before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
script:
- yarn run test-ci
after_script: greenkeeper-lockfile-upload
deploy:
  provider: npm
  email: marcus.mennemeier@actano.de
  api_key:
    secure: bqJI2xUC/AOKC/fB4Vq1y/C0jGAARQ2WSH+VJOByW7LLZ47WQ+gGKRbUTEUFWK8x29dzwNk72wPknXAqq0F4DS8qAVkmdb335QGpU3K2sxfpzTzZHsbdMf19L2ZLqKMygjP/AeRWpcBExLAJFAQglbyHq3WYuiPqo/h/X6U253ZRfnPeBv+U68Whb4W2RLCu+ejzwnXvSStMPdNUAGXZq2zTNyPM4UiDNpGreRn8IzJpAFYmDib8agksa1mO0WL/eT4iVmwfApbrEN2U1h6ZfjF1aAz0bzNRVRwlOH2O10Wubor2e/mLt99OVeWazZEGukgi0V01btrGLD6kNEQcRzEaw+3pqOBGiUM6sKqbJnuh3dd+BRbt5dbW2NR//0Nz6GthzmIMFQwIFio9ZcI5KDGnKH85yIdY0dY+A+drVLbQSN0zAmVapYR/GhTNJyR4tz5K4XAsLJ0LTw8ZYU8RnFVZnFlluqKx8bSpvzChPMwE6SoXlb79LbM9c6ZW821jLFeAsE/93/R6ARzJFW0oNAfZe9CsWUjQbSrU997e6ssm1D/n7Jzll7YRdoRn5iOjqxZMru4HAhbWTEGct2IWWeID2baVmNd8ZFVBnJlzCboIh0etqivNXjiR9ZSJmgjdYhIOiBTQNgINrKZCkPPz5THO+p1PXRjRExNug/YrkzM=
  on:
    tags: true
    repo: actano/yourchoice
