language: node_js

node_js:
  - "6"
  - "8"
  - "10"

cache:
    yarn: true
env:
  global:
    secure: "MYvJT6EHiECzSeBtllYkPeehNsgCpLMApM0TVyAL9BxKvL01jKwoR/KQ48Y0gm8DVMa7PjGR9N6Iu57jPxHfVR+QGNoQkFNsXWMq/Cp6pEOIhCHHqB0us2emxcfWbrJvzQ6SFUtNoAQ2U3Rgcf8ZQZOcWuGQDmYop9+pnwiAJokjTZ5u4WixBMkGm6k+naJCxNYVkCpS73kbyjilK/CY5DgL19vsrWyAUsoUr3edr91VFV7Oh2UKhidKcsaoKko+NGFerQXVivoWiYrLaEDpt4eCd3hWIShizIWd6FEpAbhBpDAd70UR0i4OVzv6GYDW1eMC2B+JnbLEZvzCdu2C4zuwgBwS2897mPAh2nCfJt8HLyksRlq7x7p70HQdQjMce8nQeuMa81FLa+AXJZAQVJOtwVybdWgScsERPTqZEurgv3Cy88PTvKQ7Zgx+sbhVrUagpbyMvAcZ8VmqfL829GWWaBj6ih+ZNUGq5XCaBu8zrG8L9yicE8inEHgxhO09kbMKAa9qHFfRODy+qJkE70aDH2gqaclk0VVd7FqgaJsdYRVEzBUelErL8uCc4vMbgCwtdGA05ZptZ2useQHOq4s627qpNtTpGvkGUTpcZaYFPodNpFCtTQV0fvYAzZq0SnqqJasDzNehLwGMtI9rhzgsg12k85kW/klCtbFU4Us="

before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
script:
- yarn run test-ci
after_script: greenkeeper-lockfile-upload

script:
  - yarn run test-ci

deploy:
  provider: npm
  email: marcus.mennemeier@actano.de
  api_key:
    secure: a8SApqusqcrtWNaKOP7CeAgiNs3l+dugdZVFlMlgxrL48gbqZgQJzG8auU2rkjWu9Rlq9IehNgehTIQhD48V/aabc6gbEt0NmiAO+Xuwyhhr7XCEltK1XUIJjDK/mNcWLKpNbZW3wDDj+v9eOSCU524JlGG2CKw8EXz4V66L733fEUtQKJi2dQl4fNspe1lban+c3maOj5syDDfKSABcl+KDQHZMWdmzQNtGirwvkaztlsa6m9u6IZwjTNylAf+sHtpDBh4gD/7PTCfJlE4F0X6jPHx2L91FoOwL0z3w/E7R4CNsaLKB8ZMRe3AggOxRUDb+vY5DHLPZl4CPr2cPJXhXJf6Lun4lU3vbQRjUftpo16sGjcgWAIeK3iSikGcOha+syx7T2NkIp5j6dQhBK6Qiz7wE676Zen06imKyZlWGRl4s3yE7+0BsSim3/SRBVxvlOrsJg94OIxbb8zFjrlJJE21QQc24xVbWTGcfKlauwYFv9aEBUMWVYBKjE7T0+P+j51bR6iQWK5+epJ1mw83RVhJ398csgFffxohbVwk5EhTxYyhB+2R1BSzHcvXN7gcgZ/idbuHfUTsSYhWRtPYMlREkIuLHIlWGcD8xDNSvsQjXJe+JCR/5y61KNqrqZr5Cid6nmm46NU/lrJhMi/i4MCtpZh6NEptV5nQ0FFc=
  on:
    tags: true
    repo: actano/yourchoice
